ci: Add validate tag job at the start of `release.yml` workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,8 +7,22 @@ on:
 permissions: {}
 
 jobs:
+  validate-tag:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate tag name
+        shell: bash
+        run: |
+          TAG="${GITHUB_REF#refs/tags/}"
+          VALID_TAG_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)\.[0-9]+)?$"
+          if ! [[ $TAG =~ $VALID_TAG_REGEX ]]; then
+            echo "Invalid tag name '$TAG'"
+            exit 1
+          fi
+
   prepare-notes:
     runs-on: ubuntu-latest
+    needs: [validate-tag]
     permissions:
       contents: read
     steps:
@@ -32,12 +46,13 @@ jobs:
 
   build-binaries:
     uses: ./.github/workflows/build-binaries.yml
+    needs: [validate-tag]
     permissions:
       contents: read
 
   build-containers:
     uses: ./.github/workflows/build-containers.yml
-    needs: [prepare-notes, build-binaries]
+    needs: [validate-tag, prepare-notes, build-binaries]
     permissions:
       contents: read
     secrets:
@@ -45,7 +60,7 @@ jobs:
 
   create-release:
     runs-on: ubuntu-latest
-    needs: [prepare-notes, build-binaries, build-containers]
+    needs: [validate-tag, prepare-notes, build-binaries, build-containers]
     permissions:
       contents: write
     steps:
