build(docker),ci: Add AOT variant for container images and pre-built binaries

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,22 +7,33 @@ on:
 permissions: {}
 
 jobs:
-  validate-tag:
+  setup-vars:
     runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.vars.outputs.version }}
+      is_pre: ${{ contains(steps.vars.outputs.version, '-') && 'true' || 'false' }}
+      is_latest: >-
+        ${{
+        startsWith(steps.vars.outputs.version, format('{0}.', vars.LATEST_MAJOR_MINOR))
+        && !contains(steps.vars.outputs.version, '-')
+        && 'true' || 'false'
+        }}
     steps:
-      - name: Validate tag name
+      - name: Set up vars
+        id: vars
         shell: bash
         run: |
-          TAG="${GITHUB_REF#refs/tags/}"
-          VALID_TAG_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)\.[0-9]+)?$"
-          if ! [[ $TAG =~ $VALID_TAG_REGEX ]]; then
-            echo "Invalid tag name '$TAG'"
-            exit 1
+          VERSION="${GITHUB_REF#refs/tags/v}"
+          VALID_VERSION_REGEX="^[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)\.[0-9]+)?$"
+          if ! [[ $VERSION =~ $VALID_VERSION_REGEX ]]; then
+            echo "Invalid tag name 'v${VERSION}'"
+            exit 10
           fi
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
 
   prepare-notes:
     runs-on: ubuntu-latest
-    needs: [validate-tag]
+    needs: [setup-vars]
     permissions:
       contents: read
     steps:
@@ -31,8 +42,8 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           REPO: ${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}
+          VER: ${{ needs.setup-vars.outputs.version }}
         run: |
-          VER="${GITHUB_REF#refs/tags/v}"
           gh api -H "Accept: application/vnd.github.raw+text" "repos/$REPO/contents/CHANGELOG.md?ref=v${VER}" > CHANGELOG.md
           csplit -f CHANGELOG_ CHANGELOG.md '/^## \[[0-9]\+\.[0-9]\+\.[0-9]\+\(-[a-z0-9.]\+\)\?\] - [0-9]\+-[0-9]\+-[0-9]\+/' '{1}'
           mv CHANGELOG_01 NOTES
@@ -46,13 +57,13 @@ jobs:
 
   build-binaries:
     uses: ./.github/workflows/build-binaries.yml
-    needs: [validate-tag]
+    needs: [setup-vars]
     permissions:
       contents: read
 
   build-containers:
     uses: ./.github/workflows/build-containers.yml
-    needs: [validate-tag, prepare-notes, build-binaries]
+    needs: [setup-vars, prepare-notes, build-binaries]
     permissions:
       contents: read
     secrets:
@@ -60,17 +71,10 @@ jobs:
 
   create-release:
     runs-on: ubuntu-latest
-    needs: [validate-tag, prepare-notes, build-binaries, build-containers]
+    needs: [setup-vars, prepare-notes, build-binaries, build-containers]
     permissions:
       contents: write
     steps:
-      - name: Set up vars
-        id: vars
-        shell: bash
-        run: |
-          app_version="${GITHUB_REF#refs/tags/v}"
-          echo "app_version=${app_version}" >> $GITHUB_OUTPUT
-
       - name: Download release notes
         uses: actions/download-artifact@v5
         with:
@@ -89,12 +93,8 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           REPO: ${{ vars.REPO_OWNER }}/${{ vars.REPO_NAME }}
-          VER: ${{ steps.vars.outputs.app_version }}
-          PRE: ${{ contains(steps.vars.outputs.app_version, '-') }}
-          LATEST: >-
-            ${{
-            startsWith(steps.vars.outputs.app_version, format('{0}.', vars.LATEST_MAJOR_MINOR))
-            && !contains(steps.vars.outputs.app_version, '-')
-            }}
+          VER: ${{ needs.setup-vars.outputs.version }}
+          PRE: ${{ needs.setup-vars.outputs.is_pre }}
+          LATEST: ${{ needs.setup-vars.outputs.is_latest }}
         run: |
           gh release create "v${VER}" ./assets/* --verify-tag --title "v${VER}" -F ./NOTES --latest=$LATEST -p=$PRE -R "$REPO"
